### ISSUE TITLE
What is the Twitter hashtag for this summit?

### ISSUE THREAD

**Issue by jsakamoto** [ShoCodeJP/ShoCode#11]
[`#shocode`](https://twitter.com/search?q=%23shocode&src=typed_query&f=top)? [`#shonancode`](https://twitter.com/search?q=%23shonancode&src=typed_query&f=top)?

**Comment by drewby** [comment]
Let's use #shocode since that's the short nickname for the event.

**Comment by jsakamoto** [comment]
Sounds good. Thank you!
